### ISSUE TITLE
Other Auth Solutions for Dashboards

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/test-things#36]
Currently, the dashboards are accessed through BasicAuth. It is fine but it means sharing a password so it would be better to use something like GitHub account based authorization solutions.

**Comment by relu91** [comment]
if we just need integration with Github I think we should just check the support for OIDC.

**Comment by egekorkan** [comment]
GitHub be the easy choice as we can put a rule like "anyone with write access can get access to this dashboard"

**Comment by hasanheroglu** [comment]
I have been busy investigating this for the last couple of days. It is possible to do role-based routing with the load-balancer Traefik service, but no middleware would do that now. 

- Option 1:  Here we could write a Traefik-plugin that authenticates a user via GitHub OAuth and then checks the authenticated user's permissions on a given organization and repository. Additionally, giving the required permissions as input would be nice so that the plugin would be highly customizable. Chaining the middleware is possible, and OAuth authenticator middleware already exists, so we need to implement the reading permissions part. This option requires more research, implementation, and time.

- Option 2: We authenticate users via GitHub and allowlist certain emails. Therefore, we can add collabs' emails to the allowlist, and they can access the service dashboards.

- Option 3: We might not necessarily need UIs for Prometheus, cAdvisor, and Traefik since we can create dashboards for them in Grafana. For Grafana and Portainer, we can set the OAuth mechanism in their UI. I am not sure about Portainer, but in Grafana, it is also possible to map roles from GitHub depending on the organization of authenticated users, etc.

I like option 3, which is easier to implement and use. It is also good that users do not need to switch between the Traefik dashboard, Prometheus UI, cAdvisor, and Grafana but see everything from Grafana UI. Since we will create the Grafana dashboards, we can exclude redundant data and graphs.

Let me know what you think.

**Comment by egekorkan** [comment]
After talking with @hasanheroglu , I think that the option 2 within Grafana (mix of 2 and 3) makes the most sense. The other UIs will not be exposed to anyone and doing this way allows us to give access to anyone we like based on their emails. Going with option 1 would limit the access to committers only and would give access to Eclipse admins (not needed at this stage).
